-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01' 

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE >= '2022-03-01' and SALES_DATE < '2022-04-01' 

# ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;


-- 2022년 3월의 오프라인/온라인 상품 판매 데이터 
-- 판매 날짜, 상품ID, 유저ID, 판매량
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 로 표시
-- 판매일을 기준으로 오름차순 정렬 -> 판매일이 같다면 상품 ID를 기준으로 오름차순-> 상품ID까지 같다면 유저 ID를 기준으로 오름차순 정렬 

select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where YEAR(SALES_DATE) = 2022  and MONTH(SALES_DATE) =3
UNION ALL
select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where YEAR(SALES_DATE) = 2022  and MONTH(SALES_DATE) = 3
order by SALES_DATE asc, PRODUCT_ID asc, USER_ID asc;
