-- 코드를 입력하세요
# SELECT LEFT(PRODUCT_CODE, 2), COUNT(*) AS PRODUCTS
# FROM PRODUCT
# GROUP BY LEFT(PRODUCT_CODE, 2)
# ORDER BY PRODUCT_CODE;

-- 카테고리 코드별 상품 개수
select left(PRODUCT_CODE, 2) as CATEGORY, count(PRODUCT_ID) AS COUNT
from PRODUCT
group by CATEGORY
order by CATEGORY;