# SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM BOOK
# WHERE CATEGORY = '인문' AND PUBLISHED_DATE LIKE '2021%'
# ORDER BY PUBLISHED_DATE;

select BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
from BOOK
where YEAR(PUBLISHED_DATE) = 2021 and CATEGORY = '인문'
order by PUBLISHED_DATE;

-- 도서 ID, 출판일
-- 2021년, '인문'
-- 출판일 기준 오름차순 정렬
